export const FOUND_BARS = 'FOUND_BARS';
export const GOT_LAST_SEARCHED_LOCATION = 'GOT_LAST_SEARCHED_LOCATION';
export const STARTED_SEARCH = 'STARTED_SEARCH';
export const ENDED_SEARCH = 'ENDED_SEARCH';
export const BAR_GOERS_UPDATED = 'BAR_GOERS_UPDATED';
